from os.path import join
"""Chopper rule
PycoQC computes metrics and generates interactive QC plots for Oxford
Nanopore technologies sequencing data PycoQC relies on the 
sequencing_summary.txt file generated by Albacore and Guppy, but if
needed it can also generate a summary file from basecalled fast5
files. The package supports 1D and 1D2 runs generated with Minion,
Gridion and Promethion devices, basecalled with Albacore 1.2.1+
or Guppy 2.1.3+. 
Full documentation is available at https://a-slide.github.io/pycoQC

Intended to be used:

- directly after sequencing

rule author:
    J. Gray

version:
    v0.01

tool_website:
    https://github.com/a-slide/pycoQC
"""


rule pycoqc:
    input:
        "sequencing_summary.txt"
    output:
        "{sequence_run}_16s_sequencing.html"
    conda:
        "../envs/pycoqc.yaml"
    message:
        "Executing qc sequencing runs"
    shell:
        """pycoQC -f {input} \
        -o {output}
        """
